# This workflow builds docker images and pushes them to a Docker Hub Repository
# This workflow is specific to the base-notebook directory and image
# Set the workflow name
name: Build & push container image

# Define the trigger that starts the action
# For this workflow the trigger is on a push that changes anything in the configs/jupyter/base-notebook/ path
on:
  push:
    branches:
      - main

# Define the actions that are going to take place as part of this workflow    
jobs:
  # Name the job(s)
  podman-build-push-image:
    # Define where the job should run in this case it will be run on the latest ubuntu image
    runs-on: self-hosted
    # Set the steps to take in order
    steps:
      # Step 1 is to checkout the github repo used to build the Dockerfile
      - name: Check out the repo
        uses: actions/checkout@v4
      # Get the date to apply to image tag
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d.%H')" >> $GITHUB_OUTPUT
      - name: Build Podman image
        run: |
          podman build -f Containerfile -t hub.k8s.ucar.edu/ncote/pythia24-viz:${{ steps.date.outputs.date }} . --no-cache --format=docker
      - name: Login to Harbor
        run: podman login hub.k8s.ucar.edu -u robot-ncote+pythia24-viz-site -p ${{ secrets.HARBOR_LOGIN  }}
      - name: Push Podman image to Docker hub
        run: |
          podman push hub.k8s.ucar.edu/ncote/pythia24-viz:${{ steps.date.outputs.date }}
      - name: Update Helm values.yaml
        run: | 
          sed -i '15d' app-helm-chart/values.yaml
          echo "    image: hub.k8s.ucar.edu/ncote/pythia24-viz:${{ steps.date.outputs.date }}" >> app-helm-chart/values.yaml
      - name: Update Helm Chart.yaml
        run: | 
          sed -i '24d' app-helm-chart/Chart.yaml
          echo "appVersion: '${{ steps.date.outputs.date }}'" >> app-helm-chart/Chart.yaml
      - name: Run python script to update version by 1
        run: python app-helm-chart/update_ver.py
      - name: Commit changes to main branch
        run: |
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "$GITHUB_ACTOR"
          git commit -a -m "Update Helm chart via GH Actions"
          git push